name = "Borderlands 2"
home = "https://discord.com/channels/1085716850370957462/1164256699608219698"
default_url = "https://github.com/EdricY/Bouncy-Loot-God/releases/download/v0.5/borderlands2.apworld"
tags = ["ad"]

[versions]
"0.5.0" = {}
