name = "Hi-Fi RUSH"
home = "https://discord.com/channels/731205301247803413/1223862313145073674"
default_url = "https://github.com/TRPG0/HbkArchipelago/releases/download/{{version}}/hi_fi_rush.apworld"

[versions]
"0.2.0" = {}
"0.2.1" = {}
