name = "Rift of the Necrodancer"
home = "https://discord.com/channels/731205301247803413/1337112354130759757"
default_url = "https://github.com/studkid/RiftArchipelago/releases/download/v{{version}}/rotn.apworld"

[versions]
"0.9.0" = {}
"0.10.0" = {}
